export const ROLE = {
  CANDIDATE: 'CANDIDATE',
  COMPANY: 'COMPANY',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof ROLE)[keyof typeof ROLE];

export const APPLICATION_STATUS = {
  APPLIED: 'APPLIED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_DONE: 'INTERVIEW_DONE',
  OFFER_EXTENDED: 'OFFER_EXTENDED',
  HIRED: 'HIRED',
  REJECTED: 'REJECTED',
} as const;

export type ApplicationStatus = (typeof APPLICATION_STATUS)[keyof typeof APPLICATION_STATUS];

export const JOB_TYPE = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  INTERNSHIP: 'INTERNSHIP',
  CONTRACT: 'CONTRACT',
} as const;

export type JobType = (typeof JOB_TYPE)[keyof typeof JOB_TYPE];

export const COMPANY_VERIFICATION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type CompanyVerificationStatus =
  (typeof COMPANY_VERIFICATION_STATUS)[keyof typeof COMPANY_VERIFICATION_STATUS];

export const VERIFICATION_DOCUMENT_TYPE = {
  GST_CERTIFICATE: 'GST_CERTIFICATE',
  PAN: 'PAN',
  CIN: 'CIN',
  CERTIFICATE_OF_INCORPORATION: 'CERTIFICATE_OF_INCORPORATION',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
  TAX_DOCUMENT: 'TAX_DOCUMENT',
  BUSINESS_LICENSE: 'BUSINESS_LICENSE',
} as const;

export type VerificationDocumentType =
  (typeof VERIFICATION_DOCUMENT_TYPE)[keyof typeof VERIFICATION_DOCUMENT_TYPE];

export const AUDIT_ACTION = {
  COMPANY_VERIFICATION_CREATED: 'COMPANY_VERIFICATION_CREATED',
  COMPANY_VERIFICATION_SUBMITTED: 'COMPANY_VERIFICATION_SUBMITTED',
  COMPANY_VERIFICATION_APPROVED: 'COMPANY_VERIFICATION_APPROVED',
  COMPANY_VERIFICATION_REJECTED: 'COMPANY_VERIFICATION_REJECTED',
  VERIFICATION_DOCUMENT_UPLOADED: 'VERIFICATION_DOCUMENT_UPLOADED',
  VERIFICATION_DOCUMENT_VIEWED: 'VERIFICATION_DOCUMENT_VIEWED',
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_TOKEN_REFRESHED: 'AUTH_TOKEN_REFRESHED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET_COMPLETED: 'AUTH_PASSWORD_RESET_COMPLETED',
  AUTH_EMAIL_VERIFICATION_SENT: 'AUTH_EMAIL_VERIFICATION_SENT',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
} as const;

export const ACCOUNT_TOKEN_TYPE = {
  PASSWORD_RESET: 'PASSWORD_RESET',
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
} as const;

export type AccountTokenType = (typeof ACCOUNT_TOKEN_TYPE)[keyof typeof ACCOUNT_TOKEN_TYPE];
