export const ROLE = {
  CANDIDATE: 'CANDIDATE',
  COMPANY: 'COMPANY',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof ROLE)[keyof typeof ROLE];

export const APPLICATION_STATUS = {
  APPLIED: 'APPLIED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  INTERVIEW_DONE: 'INTERVIEW_DONE',
  OFFER_EXTENDED: 'OFFER_EXTENDED',
  HIRED: 'HIRED',
  REJECTED: 'REJECTED',
} as const;

export type ApplicationStatus = (typeof APPLICATION_STATUS)[keyof typeof APPLICATION_STATUS];

export const JOB_TYPE = {
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  INTERNSHIP: 'INTERNSHIP',
  CONTRACT: 'CONTRACT',
} as const;

export type JobType = (typeof JOB_TYPE)[keyof typeof JOB_TYPE];

export const COMPANY_VERIFICATION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
} as const;

export type CompanyVerificationStatus =
  (typeof COMPANY_VERIFICATION_STATUS)[keyof typeof COMPANY_VERIFICATION_STATUS];

export const VERIFICATION_DOCUMENT_TYPE = {
  GST_CERTIFICATE: 'GST_CERTIFICATE',
  PAN: 'PAN',
  CIN: 'CIN',
  CERTIFICATE_OF_INCORPORATION: 'CERTIFICATE_OF_INCORPORATION',
  ADDRESS_PROOF: 'ADDRESS_PROOF',
  BUSINESS_REGISTRATION: 'BUSINESS_REGISTRATION',
  TAX_DOCUMENT: 'TAX_DOCUMENT',
  BUSINESS_LICENSE: 'BUSINESS_LICENSE',
} as const;

export type VerificationDocumentType =
  (typeof VERIFICATION_DOCUMENT_TYPE)[keyof typeof VERIFICATION_DOCUMENT_TYPE];

export const AUDIT_ACTION = {
  COMPANY_VERIFICATION_CREATED: 'COMPANY_VERIFICATION_CREATED',
  COMPANY_VERIFICATION_SUBMITTED: 'COMPANY_VERIFICATION_SUBMITTED',
  COMPANY_VERIFICATION_APPROVED: 'COMPANY_VERIFICATION_APPROVED',
  COMPANY_VERIFICATION_REJECTED: 'COMPANY_VERIFICATION_REJECTED',
  VERIFICATION_DOCUMENT_UPLOADED: 'VERIFICATION_DOCUMENT_UPLOADED',
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
} as const;
